version: 2
jobs:
    build:
        docker:
            - image: golang:1.16.4
        working_directory: /go/src/github.com/ieee0824/getenv
        steps:
            - checkout
            - run:
                name: install packages
                command: |
                    go get -u -v ./...
            - run:
                name: run test
                command: |
                    go test ./...
